import Util.DateUtil;

import java.io.*;
import java.sql.SQLException;

public class PortfolioWriter {
    public static String generatePortfolio(Student student) throws IOException, SQLException {

        // Build path to Downloads folder
        String downloadsPath = System.getProperty("user.home") + File.separator + "Downloads";
        String fileName      = "Portfolio_" + student.getName().replace(" ", "_") + ".txt";
        String fullPath      = downloadsPath + File.separator + fileName;

        int questionsAsked = 0;
        int questionsAnswered = 0;
        int learningRequests = 0;
        int completedSessions = 0;

        FileWriter   fw  = new FileWriter(fullPath);
        BufferedWriter bw = new BufferedWriter(fw);

        bw.write("============================================================");
        bw.newLine();
        bw.write("              SKILLBRIDGE - STUDENT PORTFOLIO               ");
        bw.newLine();
        bw.write("============================================================");
        bw.newLine();bw.newLine();
        bw.write("  PERSONAL INFORMATION");bw.newLine();
        bw.write("  --------------------");bw.newLine();
        bw.write("  Name    : " + student.getName());bw.newLine();
        bw.write("  Email   : " + student.getEmail());bw.newLine();
        bw.write("  Branch  : " + student.getBranch());bw.newLine();
        bw.write("  Phone   : " + student.getPhone());bw.newLine();
        bw.newLine();bw.newLine();
        bw.write("  PERFORMANCE SUMMARY");bw.newLine();
        bw.write("  -------------------");bw.newLine();
        bw.write(String.format("  Average Rating    : %.2f / 5.00", student.getAverageRating()));
        bw.newLine();
        bw.write("  Total Sessions    : " + student.getTotalSessions());bw.newLine();
        bw.newLine();bw.newLine();
        bw.write("  ACTIVITY SUMMARY");bw.newLine();
        bw.write("  ----------------");bw.newLine();
        bw.write("  Questions Asked   : " + questionsAsked);bw.newLine();
        bw.write("  Questions Answered: " + questionsAnswered);bw.newLine();
        bw.write("  Learning Requests : " + learningRequests);bw.newLine();
        bw.write("  Completed Sessions: " + completedSessions);bw.newLine();
        bw.newLine();bw.newLine();
        bw.write("  Generated On      : " + DateUtil.getCurrentDateDisplay());bw.newLine();
        bw.newLine();bw.newLine();
        bw.write("============================================================");bw.newLine();
        bw.write("              Generated by SkillBridge System               ");bw.newLine();
        bw.write("============================================================");bw.newLine();

        bw.close();
        return fullPath;
    }
}
